# -*- encoding: utf-8 -*-

"""
NetworkCanvas - Custom Dash Component (Python Wrapper)
======================================================

Thin :class:`dash.development.base_component.Component` subclass that
declares the prop contract for the JavaScript :class:`NetworkCanvas`
React component shipped in ``arcline_d3.js``.

Props (in)
----------
* ``nodes``       - list of ``{hashKey, kind, name, lat, lng, color,
                    icon, ...}``
* ``edges``       - list of ``{hashKey, kind, srcKey, dstKey, color,
                    width, ...}``
* ``theme``       - mapping of token name -> CSS colour string
                    (forwarded to the SVG so the canvas blends with
                    the active dark / light theme)
* ``iconBase``    - URL prefix where icon PNGs live
                    (``/assets/icons/``)
* ``layoutMode``  - one of ``force`` | ``tiered`` | ``geo``
* ``selectedId``  - currently selected entity id (highlighted ring)
* ``connectMode`` - boolean; when true, dragging from a node creates
                    a transient edge that resolves on drop
* ``ts``          - integer tick; bump from Python to force re-render

Props (out, written via ``setProps``)
-------------------------------------
* ``clickedElement``    - ``{kind, hashKey, ts}``
* ``dblClickedElement`` - ``{kind, hashKey, ts}``
* ``contextElement``    - ``{kind, hashKey, ts, x, y}`` for right-click
* ``pendingEdge``       - ``{srcKey, dstKey, ts}`` resolved drag-connect
* ``positions``         - mapping ``hashKey -> {x, y}`` after layout
"""

from typing import Any

from dash.development.base_component import Component


class NetworkCanvas(Component):
    """
    Custom Dash component rendering the network as an interactive D3
    canvas. Constructed exactly like any autogenerated Dash component.
    """

    _children_props : list = []
    _base_nodes : list = ["children"]
    _namespace : str = "arcline_d3"
    _type : str = "NetworkCanvas"
    _prop_names : tuple = (
        "id",
        "nodes",
        "edges",
        "theme",
        "iconBase",
        "layoutMode",
        "selectedId",
        "connectMode",
        "ts",
        "clickedElement",
        "dblClickedElement",
        "contextElement",
        "pendingEdge",
        "positions",
        "style",
        "className",
    )
    _valid_wildcard_attributes : list = []
    available_properties : tuple = _prop_names
    available_wildcard_properties : list = []

    def __init__(
            self,
            id : Any = Component.UNDEFINED,
            nodes : Any = Component.UNDEFINED,
            edges : Any = Component.UNDEFINED,
            theme : Any = Component.UNDEFINED,
            iconBase : Any = Component.UNDEFINED,
            layoutMode : Any = Component.UNDEFINED,
            selectedId : Any = Component.UNDEFINED,
            connectMode : Any = Component.UNDEFINED,
            ts : Any = Component.UNDEFINED,
            clickedElement : Any = Component.UNDEFINED,
            dblClickedElement : Any = Component.UNDEFINED,
            contextElement : Any = Component.UNDEFINED,
            pendingEdge : Any = Component.UNDEFINED,
            positions : Any = Component.UNDEFINED,
            style : Any = Component.UNDEFINED,
            className : Any = Component.UNDEFINED,
            **kwargs : Any,
    ) -> None:
        """
        Build the component, forwarding only props that the caller
        explicitly set so Dash can distinguish ``UNDEFINED`` from
        ``None`` on the JavaScript side.
        """
        explicit = {
            "id": id,
            "nodes": nodes,
            "edges": edges,
            "theme": theme,
            "iconBase": iconBase,
            "layoutMode": layoutMode,
            "selectedId": selectedId,
            "connectMode": connectMode,
            "ts": ts,
            "clickedElement": clickedElement,
            "dblClickedElement": dblClickedElement,
            "contextElement": contextElement,
            "pendingEdge": pendingEdge,
            "positions": positions,
            "style": style,
            "className": className,
        }
        forwarded = {
            key: value for key, value in explicit.items()
            if value is not Component.UNDEFINED
        }
        forwarded.update(kwargs)
        super().__init__(**forwarded)
