# -*- encoding: utf-8 -*-

"""
arcline_d3 - Custom Dash Component Suite
========================================

This top-level package is the Python side of the ``arcline-d3`` Dash
component suite. It must live as a real top-level package (rather than
a sub-module of :mod:`arcline`) because Dash's
:class:`~dash.development.base_component.ComponentMeta` keys its
internal :class:`ComponentRegistry` on
``cls.__module__.split(".")[0]``. That same name is used as the
URL segment for ``/_dash-component-suites/<package>/<file>`` and is
the string passed to ``importlib.import_module(...)`` when Dash
collects each library's ``_js_dist`` entries at index render time.

Layout::

    arcline_d3/
        __init__.py        <- declares _js_dist + defines NetworkCanvas
        arcline_d3.js      <- ES5 React + D3 bundle served to the browser

Defining :class:`NetworkCanvas` directly inside this module ensures
``cls.__module__.split(".")[0] == "arcline_d3"`` so Dash registers
the suite correctly. The component is also re-exported from
:mod:`arcline.dashboard.d3` for backward-compatible imports.
"""

from typing import Any

from dash.development.base_component import Component


__version__ : str = "0.2.0"

_js_dist : list = [
    {
        "relative_package_path": "arcline_d3.js",
        "external_url": None,
        "namespace": "arcline_d3",
    }
]

_css_dist : list = []


class NetworkCanvas(Component):
    """
    Custom Dash component rendering an arcline supply-chain network as
    an interactive D3 canvas. Constructed exactly like any
    autogenerated Dash component.

    Props (in)
    ----------
    * ``nodes``        - list of node dicts (hashKey, kind, name, lat,
                         lng, color, icon, ...)
    * ``edges``        - list of edge dicts (hashKey, kind, srcKey,
                         dstKey, color, width, ...)
    * ``theme``        - mapping of token name -> CSS colour string
    * ``iconBase``     - URL prefix where icon PNGs live
    * ``layoutMode``   - one of ``force`` | ``tiered`` | ``geo``
    * ``selectedId``   - currently selected entity id
    * ``connectMode``  - boolean; enables drag-to-connect gesture
    * ``ts``           - integer tick; bump to force a re-render

    Props (out, written via ``setProps``)
    -------------------------------------
    * ``clickedElement``    - ``{kind, hashKey, ts}``
    * ``dblClickedElement`` - ``{kind, hashKey, ts}``
    * ``contextElement``    - ``{kind, hashKey, x, y, ts}``
    * ``pendingEdge``       - ``{srcKey, dstKey, ts}``
    * ``positions``         - mapping ``hashKey -> {x, y}``
    """

    _children_props : list = []
    _base_nodes : list = ["children"]
    _namespace : str = "arcline_d3"
    _type : str = "NetworkCanvas"
    _prop_names : tuple = (
        "id",
        "nodes",
        "edges",
        "theme",
        "iconBase",
        "layoutMode",
        "selectedId",
        "connectMode",
        "ts",
        "clickedElement",
        "dblClickedElement",
        "contextElement",
        "pendingEdge",
        "positions",
        "style",
        "className",
    )
    _valid_wildcard_attributes : list = []
    available_properties : tuple = _prop_names
    available_wildcard_properties : list = []

    def __init__(
            self,
            id : Any = Component.UNDEFINED,
            nodes : Any = Component.UNDEFINED,
            edges : Any = Component.UNDEFINED,
            theme : Any = Component.UNDEFINED,
            iconBase : Any = Component.UNDEFINED,
            layoutMode : Any = Component.UNDEFINED,
            selectedId : Any = Component.UNDEFINED,
            connectMode : Any = Component.UNDEFINED,
            ts : Any = Component.UNDEFINED,
            clickedElement : Any = Component.UNDEFINED,
            dblClickedElement : Any = Component.UNDEFINED,
            contextElement : Any = Component.UNDEFINED,
            pendingEdge : Any = Component.UNDEFINED,
            positions : Any = Component.UNDEFINED,
            style : Any = Component.UNDEFINED,
            className : Any = Component.UNDEFINED,
            **kwargs : Any,
    ) -> None:
        """
        Build the component, forwarding only props the caller
        explicitly set so Dash can distinguish ``UNDEFINED`` from
        ``None`` on the JavaScript side.
        """
        explicit = {
            "id": id,
            "nodes": nodes,
            "edges": edges,
            "theme": theme,
            "iconBase": iconBase,
            "layoutMode": layoutMode,
            "selectedId": selectedId,
            "connectMode": connectMode,
            "ts": ts,
            "clickedElement": clickedElement,
            "dblClickedElement": dblClickedElement,
            "contextElement": contextElement,
            "pendingEdge": pendingEdge,
            "positions": positions,
            "style": style,
            "className": className,
        }
        forwarded = {
            key: value for key, value in explicit.items()
            if value is not Component.UNDEFINED
        }
        forwarded.update(kwargs)
        super().__init__(**forwarded)


__all__ = ["NetworkCanvas"]
